#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="cupcake")]
	public partial class dbLQDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertbase(@base instance);
    partial void Updatebase(@base instance);
    partial void Deletebase(@base instance);
    partial void Insertvoto(voto instance);
    partial void Updatevoto(voto instance);
    partial void Deletevoto(voto instance);
    partial void Insertcrema(crema instance);
    partial void Updatecrema(crema instance);
    partial void Deletecrema(crema instance);
    partial void Insertdiseno(diseno instance);
    partial void Updatediseno(diseno instance);
    partial void Deletediseno(diseno instance);
    partial void Insertpedido(pedido instance);
    partial void Updatepedido(pedido instance);
    partial void Deletepedido(pedido instance);
    partial void Insertpedido_detalle(pedido_detalle instance);
    partial void Updatepedido_detalle(pedido_detalle instance);
    partial void Deletepedido_detalle(pedido_detalle instance);
    partial void Insertrole(role instance);
    partial void Updaterole(role instance);
    partial void Deleterole(role instance);
    partial void Inserttopping(topping instance);
    partial void Updatetopping(topping instance);
    partial void Deletetopping(topping instance);
    partial void Insertusuario(usuario instance);
    partial void Updateusuario(usuario instance);
    partial void Deleteusuario(usuario instance);
    #endregion
		
		public dbLQDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ApplicationServices"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbLQDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbLQDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbLQDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbLQDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<@base> bases
		{
			get
			{
				return this.GetTable<@base>();
			}
		}
		
		public System.Data.Linq.Table<voto> votos
		{
			get
			{
				return this.GetTable<voto>();
			}
		}
		
		public System.Data.Linq.Table<crema> cremas
		{
			get
			{
				return this.GetTable<crema>();
			}
		}
		
		public System.Data.Linq.Table<diseno> disenos
		{
			get
			{
				return this.GetTable<diseno>();
			}
		}
		
		public System.Data.Linq.Table<pedido> pedidos
		{
			get
			{
				return this.GetTable<pedido>();
			}
		}
		
		public System.Data.Linq.Table<pedido_detalle> pedido_detalles
		{
			get
			{
				return this.GetTable<pedido_detalle>();
			}
		}
		
		public System.Data.Linq.Table<role> roles
		{
			get
			{
				return this.GetTable<role>();
			}
		}
		
		public System.Data.Linq.Table<topping> toppings
		{
			get
			{
				return this.GetTable<topping>();
			}
		}
		
		public System.Data.Linq.Table<usuario> usuarios
		{
			get
			{
				return this.GetTable<usuario>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.base")]
	public partial class @base : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idbase;
		
		private string _nombre;
		
		private System.Nullable<decimal> _precio;
		
		private string _imagen;
		
		private EntitySet<diseno> _disenos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidbaseChanging(int value);
    partial void OnidbaseChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnprecioChanging(System.Nullable<decimal> value);
    partial void OnprecioChanged();
    partial void OnimagenChanging(string value);
    partial void OnimagenChanged();
    #endregion
		
		public @base()
		{
			this._disenos = new EntitySet<diseno>(new Action<diseno>(this.attach_disenos), new Action<diseno>(this.detach_disenos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idbase", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idbase
		{
			get
			{
				return this._idbase;
			}
			set
			{
				if ((this._idbase != value))
				{
					this.OnidbaseChanging(value);
					this.SendPropertyChanging();
					this._idbase = value;
					this.SendPropertyChanged("idbase");
					this.OnidbaseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(45)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this.OnprecioChanging(value);
					this.SendPropertyChanging();
					this._precio = value;
					this.SendPropertyChanged("precio");
					this.OnprecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imagen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string imagen
		{
			get
			{
				return this._imagen;
			}
			set
			{
				if ((this._imagen != value))
				{
					this.OnimagenChanging(value);
					this.SendPropertyChanging();
					this._imagen = value;
					this.SendPropertyChanged("imagen");
					this.OnimagenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="base_diseno", Storage="_disenos", ThisKey="idbase", OtherKey="idbase")]
		public EntitySet<diseno> disenos
		{
			get
			{
				return this._disenos;
			}
			set
			{
				this._disenos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_disenos(diseno entity)
		{
			this.SendPropertyChanging();
			entity.@base = this;
		}
		
		private void detach_disenos(diseno entity)
		{
			this.SendPropertyChanging();
			entity.@base = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.voto")]
	public partial class voto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idlike;
		
		private bool _positivo;
		
		private int _iddiseno;
		
		private string _idusuario;
		
		private EntityRef<usuario> _usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidlikeChanging(int value);
    partial void OnidlikeChanged();
    partial void OnpositivoChanging(bool value);
    partial void OnpositivoChanged();
    partial void OniddisenoChanging(int value);
    partial void OniddisenoChanged();
    partial void OnidusuarioChanging(string value);
    partial void OnidusuarioChanged();
    #endregion
		
		public voto()
		{
			this._usuario = default(EntityRef<usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idlike", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idlike
		{
			get
			{
				return this._idlike;
			}
			set
			{
				if ((this._idlike != value))
				{
					this.OnidlikeChanging(value);
					this.SendPropertyChanging();
					this._idlike = value;
					this.SendPropertyChanged("idlike");
					this.OnidlikeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_positivo", DbType="Bit NOT NULL")]
		public bool positivo
		{
			get
			{
				return this._positivo;
			}
			set
			{
				if ((this._positivo != value))
				{
					this.OnpositivoChanging(value);
					this.SendPropertyChanging();
					this._positivo = value;
					this.SendPropertyChanged("positivo");
					this.OnpositivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iddiseno", DbType="Int NOT NULL")]
		public int iddiseno
		{
			get
			{
				return this._iddiseno;
			}
			set
			{
				if ((this._iddiseno != value))
				{
					this.OniddisenoChanging(value);
					this.SendPropertyChanging();
					this._iddiseno = value;
					this.SendPropertyChanged("iddiseno");
					this.OniddisenoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idusuario", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string idusuario
		{
			get
			{
				return this._idusuario;
			}
			set
			{
				if ((this._idusuario != value))
				{
					if (this._usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidusuarioChanging(value);
					this.SendPropertyChanging();
					this._idusuario = value;
					this.SendPropertyChanged("idusuario");
					this.OnidusuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="usuario_voto", Storage="_usuario", ThisKey="idusuario", OtherKey="idusuario", IsForeignKey=true)]
		public usuario usuario
		{
			get
			{
				return this._usuario.Entity;
			}
			set
			{
				usuario previousValue = this._usuario.Entity;
				if (((previousValue != value) 
							|| (this._usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._usuario.Entity = null;
						previousValue.votos.Remove(this);
					}
					this._usuario.Entity = value;
					if ((value != null))
					{
						value.votos.Add(this);
						this._idusuario = value.idusuario;
					}
					else
					{
						this._idusuario = default(string);
					}
					this.SendPropertyChanged("usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.crema")]
	public partial class crema : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idcrema;
		
		private string _nombre;
		
		private System.Nullable<decimal> _precio;
		
		private string _imagen;
		
		private EntitySet<diseno> _disenos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidcremaChanging(int value);
    partial void OnidcremaChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnprecioChanging(System.Nullable<decimal> value);
    partial void OnprecioChanged();
    partial void OnimagenChanging(string value);
    partial void OnimagenChanged();
    #endregion
		
		public crema()
		{
			this._disenos = new EntitySet<diseno>(new Action<diseno>(this.attach_disenos), new Action<diseno>(this.detach_disenos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idcrema", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idcrema
		{
			get
			{
				return this._idcrema;
			}
			set
			{
				if ((this._idcrema != value))
				{
					this.OnidcremaChanging(value);
					this.SendPropertyChanging();
					this._idcrema = value;
					this.SendPropertyChanged("idcrema");
					this.OnidcremaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(45)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this.OnprecioChanging(value);
					this.SendPropertyChanging();
					this._precio = value;
					this.SendPropertyChanged("precio");
					this.OnprecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imagen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string imagen
		{
			get
			{
				return this._imagen;
			}
			set
			{
				if ((this._imagen != value))
				{
					this.OnimagenChanging(value);
					this.SendPropertyChanging();
					this._imagen = value;
					this.SendPropertyChanged("imagen");
					this.OnimagenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="crema_diseno", Storage="_disenos", ThisKey="idcrema", OtherKey="idcrema")]
		public EntitySet<diseno> disenos
		{
			get
			{
				return this._disenos;
			}
			set
			{
				this._disenos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_disenos(diseno entity)
		{
			this.SendPropertyChanging();
			entity.crema = this;
		}
		
		private void detach_disenos(diseno entity)
		{
			this.SendPropertyChanging();
			entity.crema = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.diseno")]
	public partial class diseno : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _iddiseno;
		
		private int _idtopping;
		
		private int _idcrema;
		
		private int _idbase;
		
		private string _nombre;
		
		private string _idusuario;
		
		private EntitySet<pedido_detalle> _pedido_detalles;
		
		private EntityRef<@base> _base;
		
		private EntityRef<crema> _crema;
		
		private EntityRef<topping> _topping;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OniddisenoChanging(int value);
    partial void OniddisenoChanged();
    partial void OnidtoppingChanging(int value);
    partial void OnidtoppingChanged();
    partial void OnidcremaChanging(int value);
    partial void OnidcremaChanged();
    partial void OnidbaseChanging(int value);
    partial void OnidbaseChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnidusuarioChanging(string value);
    partial void OnidusuarioChanged();
    #endregion
		
		public diseno()
		{
			this._pedido_detalles = new EntitySet<pedido_detalle>(new Action<pedido_detalle>(this.attach_pedido_detalles), new Action<pedido_detalle>(this.detach_pedido_detalles));
			this._base = default(EntityRef<@base>);
			this._crema = default(EntityRef<crema>);
			this._topping = default(EntityRef<topping>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iddiseno", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int iddiseno
		{
			get
			{
				return this._iddiseno;
			}
			set
			{
				if ((this._iddiseno != value))
				{
					this.OniddisenoChanging(value);
					this.SendPropertyChanging();
					this._iddiseno = value;
					this.SendPropertyChanged("iddiseno");
					this.OniddisenoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idtopping", DbType="Int NOT NULL")]
		public int idtopping
		{
			get
			{
				return this._idtopping;
			}
			set
			{
				if ((this._idtopping != value))
				{
					if (this._topping.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidtoppingChanging(value);
					this.SendPropertyChanging();
					this._idtopping = value;
					this.SendPropertyChanged("idtopping");
					this.OnidtoppingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idcrema", DbType="Int NOT NULL")]
		public int idcrema
		{
			get
			{
				return this._idcrema;
			}
			set
			{
				if ((this._idcrema != value))
				{
					if (this._crema.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidcremaChanging(value);
					this.SendPropertyChanging();
					this._idcrema = value;
					this.SendPropertyChanged("idcrema");
					this.OnidcremaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idbase", DbType="Int NOT NULL")]
		public int idbase
		{
			get
			{
				return this._idbase;
			}
			set
			{
				if ((this._idbase != value))
				{
					if (this._base.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidbaseChanging(value);
					this.SendPropertyChanging();
					this._idbase = value;
					this.SendPropertyChanged("idbase");
					this.OnidbaseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(45)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idusuario", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string idusuario
		{
			get
			{
				return this._idusuario;
			}
			set
			{
				if ((this._idusuario != value))
				{
					this.OnidusuarioChanging(value);
					this.SendPropertyChanging();
					this._idusuario = value;
					this.SendPropertyChanged("idusuario");
					this.OnidusuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="diseno_pedido_detalle", Storage="_pedido_detalles", ThisKey="iddiseno", OtherKey="iddiseno")]
		public EntitySet<pedido_detalle> pedido_detalles
		{
			get
			{
				return this._pedido_detalles;
			}
			set
			{
				this._pedido_detalles.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="base_diseno", Storage="_base", ThisKey="idbase", OtherKey="idbase", IsForeignKey=true)]
		public @base @base
		{
			get
			{
				return this._base.Entity;
			}
			set
			{
				@base previousValue = this._base.Entity;
				if (((previousValue != value) 
							|| (this._base.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._base.Entity = null;
						previousValue.disenos.Remove(this);
					}
					this._base.Entity = value;
					if ((value != null))
					{
						value.disenos.Add(this);
						this._idbase = value.idbase;
					}
					else
					{
						this._idbase = default(int);
					}
					this.SendPropertyChanged("@base");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="crema_diseno", Storage="_crema", ThisKey="idcrema", OtherKey="idcrema", IsForeignKey=true)]
		public crema crema
		{
			get
			{
				return this._crema.Entity;
			}
			set
			{
				crema previousValue = this._crema.Entity;
				if (((previousValue != value) 
							|| (this._crema.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._crema.Entity = null;
						previousValue.disenos.Remove(this);
					}
					this._crema.Entity = value;
					if ((value != null))
					{
						value.disenos.Add(this);
						this._idcrema = value.idcrema;
					}
					else
					{
						this._idcrema = default(int);
					}
					this.SendPropertyChanged("crema");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="topping_diseno", Storage="_topping", ThisKey="idtopping", OtherKey="idtopping", IsForeignKey=true)]
		public topping topping
		{
			get
			{
				return this._topping.Entity;
			}
			set
			{
				topping previousValue = this._topping.Entity;
				if (((previousValue != value) 
							|| (this._topping.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._topping.Entity = null;
						previousValue.disenos.Remove(this);
					}
					this._topping.Entity = value;
					if ((value != null))
					{
						value.disenos.Add(this);
						this._idtopping = value.idtopping;
					}
					else
					{
						this._idtopping = default(int);
					}
					this.SendPropertyChanged("topping");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_pedido_detalles(pedido_detalle entity)
		{
			this.SendPropertyChanging();
			entity.diseno = this;
		}
		
		private void detach_pedido_detalles(pedido_detalle entity)
		{
			this.SendPropertyChanging();
			entity.diseno = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pedido")]
	public partial class pedido : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idpedido;
		
		private string _idusuario;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private System.Nullable<System.DateTime> _fecha_entrega;
		
		private string _dir_entrega;
		
		private string _dir_factura;
		
		private System.Nullable<bool> _entregado;
		
		private System.Nullable<bool> _anulado;
		
		private System.Nullable<decimal> _cargo_extra;
		
		private System.Nullable<decimal> _subtotal;
		
		private System.Nullable<decimal> _iva;
		
		private System.Nullable<decimal> _total;
		
		private EntitySet<pedido_detalle> _pedido_detalles;
		
		private EntityRef<usuario> _usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidpedidoChanging(int value);
    partial void OnidpedidoChanged();
    partial void OnidusuarioChanging(string value);
    partial void OnidusuarioChanged();
    partial void OnfechaChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaChanged();
    partial void Onfecha_entregaChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_entregaChanged();
    partial void Ondir_entregaChanging(string value);
    partial void Ondir_entregaChanged();
    partial void Ondir_facturaChanging(string value);
    partial void Ondir_facturaChanged();
    partial void OnentregadoChanging(System.Nullable<bool> value);
    partial void OnentregadoChanged();
    partial void OnanuladoChanging(System.Nullable<bool> value);
    partial void OnanuladoChanged();
    partial void Oncargo_extraChanging(System.Nullable<decimal> value);
    partial void Oncargo_extraChanged();
    partial void OnsubtotalChanging(System.Nullable<decimal> value);
    partial void OnsubtotalChanged();
    partial void OnivaChanging(System.Nullable<decimal> value);
    partial void OnivaChanged();
    partial void OntotalChanging(System.Nullable<decimal> value);
    partial void OntotalChanged();
    #endregion
		
		public pedido()
		{
			this._pedido_detalles = new EntitySet<pedido_detalle>(new Action<pedido_detalle>(this.attach_pedido_detalles), new Action<pedido_detalle>(this.detach_pedido_detalles));
			this._usuario = default(EntityRef<usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idpedido", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idpedido
		{
			get
			{
				return this._idpedido;
			}
			set
			{
				if ((this._idpedido != value))
				{
					this.OnidpedidoChanging(value);
					this.SendPropertyChanging();
					this._idpedido = value;
					this.SendPropertyChanged("idpedido");
					this.OnidpedidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idusuario", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string idusuario
		{
			get
			{
				return this._idusuario;
			}
			set
			{
				if ((this._idusuario != value))
				{
					if (this._usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidusuarioChanging(value);
					this.SendPropertyChanging();
					this._idusuario = value;
					this.SendPropertyChanged("idusuario");
					this.OnidusuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="Date")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_entrega", DbType="Date")]
		public System.Nullable<System.DateTime> fecha_entrega
		{
			get
			{
				return this._fecha_entrega;
			}
			set
			{
				if ((this._fecha_entrega != value))
				{
					this.Onfecha_entregaChanging(value);
					this.SendPropertyChanging();
					this._fecha_entrega = value;
					this.SendPropertyChanged("fecha_entrega");
					this.Onfecha_entregaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dir_entrega", DbType="VarChar(45)")]
		public string dir_entrega
		{
			get
			{
				return this._dir_entrega;
			}
			set
			{
				if ((this._dir_entrega != value))
				{
					this.Ondir_entregaChanging(value);
					this.SendPropertyChanging();
					this._dir_entrega = value;
					this.SendPropertyChanged("dir_entrega");
					this.Ondir_entregaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dir_factura", DbType="VarChar(45)")]
		public string dir_factura
		{
			get
			{
				return this._dir_factura;
			}
			set
			{
				if ((this._dir_factura != value))
				{
					this.Ondir_facturaChanging(value);
					this.SendPropertyChanging();
					this._dir_factura = value;
					this.SendPropertyChanged("dir_factura");
					this.Ondir_facturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entregado", DbType="Bit")]
		public System.Nullable<bool> entregado
		{
			get
			{
				return this._entregado;
			}
			set
			{
				if ((this._entregado != value))
				{
					this.OnentregadoChanging(value);
					this.SendPropertyChanging();
					this._entregado = value;
					this.SendPropertyChanged("entregado");
					this.OnentregadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anulado", DbType="Bit")]
		public System.Nullable<bool> anulado
		{
			get
			{
				return this._anulado;
			}
			set
			{
				if ((this._anulado != value))
				{
					this.OnanuladoChanging(value);
					this.SendPropertyChanging();
					this._anulado = value;
					this.SendPropertyChanged("anulado");
					this.OnanuladoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cargo_extra", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> cargo_extra
		{
			get
			{
				return this._cargo_extra;
			}
			set
			{
				if ((this._cargo_extra != value))
				{
					this.Oncargo_extraChanging(value);
					this.SendPropertyChanging();
					this._cargo_extra = value;
					this.SendPropertyChanged("cargo_extra");
					this.Oncargo_extraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subtotal", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> subtotal
		{
			get
			{
				return this._subtotal;
			}
			set
			{
				if ((this._subtotal != value))
				{
					this.OnsubtotalChanging(value);
					this.SendPropertyChanging();
					this._subtotal = value;
					this.SendPropertyChanged("subtotal");
					this.OnsubtotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iva", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> iva
		{
			get
			{
				return this._iva;
			}
			set
			{
				if ((this._iva != value))
				{
					this.OnivaChanging(value);
					this.SendPropertyChanging();
					this._iva = value;
					this.SendPropertyChanged("iva");
					this.OnivaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this.OntotalChanging(value);
					this.SendPropertyChanging();
					this._total = value;
					this.SendPropertyChanged("total");
					this.OntotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pedido_pedido_detalle", Storage="_pedido_detalles", ThisKey="idpedido", OtherKey="idpedido")]
		public EntitySet<pedido_detalle> pedido_detalles
		{
			get
			{
				return this._pedido_detalles;
			}
			set
			{
				this._pedido_detalles.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="usuario_pedido", Storage="_usuario", ThisKey="idusuario", OtherKey="idusuario", IsForeignKey=true)]
		public usuario usuario
		{
			get
			{
				return this._usuario.Entity;
			}
			set
			{
				usuario previousValue = this._usuario.Entity;
				if (((previousValue != value) 
							|| (this._usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._usuario.Entity = null;
						previousValue.pedidos.Remove(this);
					}
					this._usuario.Entity = value;
					if ((value != null))
					{
						value.pedidos.Add(this);
						this._idusuario = value.idusuario;
					}
					else
					{
						this._idusuario = default(string);
					}
					this.SendPropertyChanged("usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_pedido_detalles(pedido_detalle entity)
		{
			this.SendPropertyChanging();
			entity.pedido = this;
		}
		
		private void detach_pedido_detalles(pedido_detalle entity)
		{
			this.SendPropertyChanging();
			entity.pedido = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[pedido.detalle]")]
	public partial class pedido_detalle : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _iddetalle;
		
		private int _iddiseno;
		
		private int _idpedido;
		
		private int _cantidad;
		
		private decimal _precio;
		
		private EntityRef<diseno> _diseno;
		
		private EntityRef<pedido> _pedido;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OniddetalleChanging(int value);
    partial void OniddetalleChanged();
    partial void OniddisenoChanging(int value);
    partial void OniddisenoChanged();
    partial void OnidpedidoChanging(int value);
    partial void OnidpedidoChanged();
    partial void OncantidadChanging(int value);
    partial void OncantidadChanged();
    partial void OnprecioChanging(decimal value);
    partial void OnprecioChanged();
    #endregion
		
		public pedido_detalle()
		{
			this._diseno = default(EntityRef<diseno>);
			this._pedido = default(EntityRef<pedido>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iddetalle", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int iddetalle
		{
			get
			{
				return this._iddetalle;
			}
			set
			{
				if ((this._iddetalle != value))
				{
					this.OniddetalleChanging(value);
					this.SendPropertyChanging();
					this._iddetalle = value;
					this.SendPropertyChanged("iddetalle");
					this.OniddetalleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iddiseno", DbType="Int NOT NULL")]
		public int iddiseno
		{
			get
			{
				return this._iddiseno;
			}
			set
			{
				if ((this._iddiseno != value))
				{
					if (this._diseno.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OniddisenoChanging(value);
					this.SendPropertyChanging();
					this._iddiseno = value;
					this.SendPropertyChanged("iddiseno");
					this.OniddisenoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idpedido", DbType="Int NOT NULL")]
		public int idpedido
		{
			get
			{
				return this._idpedido;
			}
			set
			{
				if ((this._idpedido != value))
				{
					if (this._pedido.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidpedidoChanging(value);
					this.SendPropertyChanging();
					this._idpedido = value;
					this.SendPropertyChanged("idpedido");
					this.OnidpedidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int NOT NULL")]
		public int cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="Decimal(18,2) NOT NULL")]
		public decimal precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this.OnprecioChanging(value);
					this.SendPropertyChanging();
					this._precio = value;
					this.SendPropertyChanged("precio");
					this.OnprecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="diseno_pedido_detalle", Storage="_diseno", ThisKey="iddiseno", OtherKey="iddiseno", IsForeignKey=true)]
		public diseno diseno
		{
			get
			{
				return this._diseno.Entity;
			}
			set
			{
				diseno previousValue = this._diseno.Entity;
				if (((previousValue != value) 
							|| (this._diseno.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._diseno.Entity = null;
						previousValue.pedido_detalles.Remove(this);
					}
					this._diseno.Entity = value;
					if ((value != null))
					{
						value.pedido_detalles.Add(this);
						this._iddiseno = value.iddiseno;
					}
					else
					{
						this._iddiseno = default(int);
					}
					this.SendPropertyChanged("diseno");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pedido_pedido_detalle", Storage="_pedido", ThisKey="idpedido", OtherKey="idpedido", IsForeignKey=true)]
		public pedido pedido
		{
			get
			{
				return this._pedido.Entity;
			}
			set
			{
				pedido previousValue = this._pedido.Entity;
				if (((previousValue != value) 
							|| (this._pedido.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._pedido.Entity = null;
						previousValue.pedido_detalles.Remove(this);
					}
					this._pedido.Entity = value;
					if ((value != null))
					{
						value.pedido_detalles.Add(this);
						this._idpedido = value.idpedido;
					}
					else
					{
						this._idpedido = default(int);
					}
					this.SendPropertyChanged("pedido");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.roles")]
	public partial class role : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idrol;
		
		private string _nombre;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidrolChanging(int value);
    partial void OnidrolChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    #endregion
		
		public role()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idrol", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idrol
		{
			get
			{
				return this._idrol;
			}
			set
			{
				if ((this._idrol != value))
				{
					this.OnidrolChanging(value);
					this.SendPropertyChanging();
					this._idrol = value;
					this.SendPropertyChanged("idrol");
					this.OnidrolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(45)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.topping")]
	public partial class topping : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idtopping;
		
		private string _nombre;
		
		private System.Nullable<decimal> _precio;
		
		private string _imagen;
		
		private EntitySet<diseno> _disenos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidtoppingChanging(int value);
    partial void OnidtoppingChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnprecioChanging(System.Nullable<decimal> value);
    partial void OnprecioChanged();
    partial void OnimagenChanging(string value);
    partial void OnimagenChanged();
    #endregion
		
		public topping()
		{
			this._disenos = new EntitySet<diseno>(new Action<diseno>(this.attach_disenos), new Action<diseno>(this.detach_disenos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idtopping", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idtopping
		{
			get
			{
				return this._idtopping;
			}
			set
			{
				if ((this._idtopping != value))
				{
					this.OnidtoppingChanging(value);
					this.SendPropertyChanging();
					this._idtopping = value;
					this.SendPropertyChanged("idtopping");
					this.OnidtoppingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(45)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this.OnprecioChanging(value);
					this.SendPropertyChanging();
					this._precio = value;
					this.SendPropertyChanged("precio");
					this.OnprecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imagen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string imagen
		{
			get
			{
				return this._imagen;
			}
			set
			{
				if ((this._imagen != value))
				{
					this.OnimagenChanging(value);
					this.SendPropertyChanging();
					this._imagen = value;
					this.SendPropertyChanged("imagen");
					this.OnimagenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="topping_diseno", Storage="_disenos", ThisKey="idtopping", OtherKey="idtopping")]
		public EntitySet<diseno> disenos
		{
			get
			{
				return this._disenos;
			}
			set
			{
				this._disenos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_disenos(diseno entity)
		{
			this.SendPropertyChanging();
			entity.topping = this;
		}
		
		private void detach_disenos(diseno entity)
		{
			this.SendPropertyChanging();
			entity.topping = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.usuarios")]
	public partial class usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idusuario;
		
		private string _nombre;
		
		private string _telefono;
		
		private string _dui;
		
		private string _correo;
		
		private string _clave;
		
		private bool _admin;
		
		private EntitySet<voto> _votos;
		
		private EntitySet<pedido> _pedidos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidusuarioChanging(string value);
    partial void OnidusuarioChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    partial void OnduiChanging(string value);
    partial void OnduiChanged();
    partial void OncorreoChanging(string value);
    partial void OncorreoChanged();
    partial void OnclaveChanging(string value);
    partial void OnclaveChanged();
    partial void OnadminChanging(bool value);
    partial void OnadminChanged();
    #endregion
		
		public usuario()
		{
			this._votos = new EntitySet<voto>(new Action<voto>(this.attach_votos), new Action<voto>(this.detach_votos));
			this._pedidos = new EntitySet<pedido>(new Action<pedido>(this.attach_pedidos), new Action<pedido>(this.detach_pedidos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idusuario", DbType="NVarChar(256) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idusuario
		{
			get
			{
				return this._idusuario;
			}
			set
			{
				if ((this._idusuario != value))
				{
					this.OnidusuarioChanging(value);
					this.SendPropertyChanging();
					this._idusuario = value;
					this.SendPropertyChanged("idusuario");
					this.OnidusuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(45)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="VarChar(8)")]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dui", DbType="VarChar(10)")]
		public string dui
		{
			get
			{
				return this._dui;
			}
			set
			{
				if ((this._dui != value))
				{
					this.OnduiChanging(value);
					this.SendPropertyChanging();
					this._dui = value;
					this.SendPropertyChanged("dui");
					this.OnduiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(100)")]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this.OncorreoChanging(value);
					this.SendPropertyChanging();
					this._correo = value;
					this.SendPropertyChanged("correo");
					this.OncorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clave", DbType="VarChar(50)")]
		public string clave
		{
			get
			{
				return this._clave;
			}
			set
			{
				if ((this._clave != value))
				{
					this.OnclaveChanging(value);
					this.SendPropertyChanging();
					this._clave = value;
					this.SendPropertyChanged("clave");
					this.OnclaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin", DbType="Bit NOT NULL")]
		public bool admin
		{
			get
			{
				return this._admin;
			}
			set
			{
				if ((this._admin != value))
				{
					this.OnadminChanging(value);
					this.SendPropertyChanging();
					this._admin = value;
					this.SendPropertyChanged("admin");
					this.OnadminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="usuario_voto", Storage="_votos", ThisKey="idusuario", OtherKey="idusuario")]
		public EntitySet<voto> votos
		{
			get
			{
				return this._votos;
			}
			set
			{
				this._votos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="usuario_pedido", Storage="_pedidos", ThisKey="idusuario", OtherKey="idusuario")]
		public EntitySet<pedido> pedidos
		{
			get
			{
				return this._pedidos;
			}
			set
			{
				this._pedidos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_votos(voto entity)
		{
			this.SendPropertyChanging();
			entity.usuario = this;
		}
		
		private void detach_votos(voto entity)
		{
			this.SendPropertyChanging();
			entity.usuario = null;
		}
		
		private void attach_pedidos(pedido entity)
		{
			this.SendPropertyChanging();
			entity.usuario = this;
		}
		
		private void detach_pedidos(pedido entity)
		{
			this.SendPropertyChanging();
			entity.usuario = null;
		}
	}
}
#pragma warning restore 1591
